FROM golang:1.14 AS builder

RUN mkdir -p /go/src/drone-delivery/simulation
RUN go get -u github.com/cosmtrek/air

COPY go.mod /go/src/drone-delivery/simulation
COPY go.sum /go/src/drone-delivery/simulation
WORKDIR /go/src/drone-delivery/simulation
RUN go mod download
#RUN go install
COPY ./ /go/src/drone-delivery/simulation
#hot reload
ENTRYPOINT ["air", "-c", ".air.toml", "-d"]
EXPOSE 3000