version: '3'
services:
#  redis:
#    image: 'redis:latest'
  postgres:
    build:
      dockerfile: Dockerfile
      context: ./databases/postgres
    ports:
    - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
  server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    depends_on:
      - postgres
    links:
      - postgres
    ports:
    - '5000:5000'
    environment:
      - PGUSER=postgres
      - PGHOST=host.docker.internal
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGPASSWORD=postgres
#      todo: itt majd lesz több adatbázis is, mert ugye össze kell hasonlítani
  warehouse:
    build:
      dockerfile: Dockerfile
      context: ./warehouse
    depends_on:
      - server
    ports:
    - '8080'
  simulation:
    build:
      dockerfile: Dockerfile
      context: ./simulation
    depends_on:
      - warehouse
      - server